version: 2

jobs:
  build:
    docker:
    - image: circleci/node:10.15-browsers-legacy
    environment:
      WP_VERSION: "5.0"
      MYSQL_DATABASE: wptest
      MYSQL_USER: wptest
      MYSQL_PASSWORD: wptest
    steps:
    - run:
        name: Downloading WP
        command: wget -nv -O /tmp/wordpress.tar.gz https://github.com/WordPress/wordpress-develop/tarball/$WP_VERSION
    - run:
        name: Extracting WP from tarball
        command: tar --strip-components=1 -zxmf /tmp/wordpress.tar.gz -C .
    - restore_cache:
        keys:
        - v1-node-dependencies
    - run:
        name: Installing Grunt
        command: sudo npm install -g grunt
    - run:
        name: Installing dependencies
        command: npm install -f
    - run:
        name: Build project
        command: grunt -f
    - save_cache:
        paths:
        - ./node_modules/
        key: v1-node-dependencies
    - checkout:
        path: build/wp-content/plugins/swiftype-search
    - run:
        name: Updating wp-test-config.php
        command: |
          cat wp-tests-config-sample.php |
          sed "s/youremptytestdbnamehere/$MYSQL_DATABASE/" |
          sed "s/yourusernamehere/$MYSQL_USER/" |
          sed "s/yourpasswordhere/$MYSQL_PASSWORD/" |
          sed "s/localhost/127.0.0.1/" > wp-tests-config.php
    - persist_to_workspace:
        root: .
        paths:
        - .

  test:
    docker:
    - image: circleci/php:7.1-browsers
    - image: mysql:5.7
      environment:
        MYSQL_DATABASE: wptest
        MYSQL_USER: wptest
        MYSQL_PASSWORD: wptest
        MYSQL_RANDOM_ROOT_PASSWORD: "true"
    steps:
    - attach_workspace:
        at: .
    - restore_cache:
        keys:
        - v1-composer-dependencies
    - run:
        name: Installing PHP Unit
        command: composer global require phpunit/phpunit:^6.0
    - run:
        name: Running unit tests
        command: ~/.composer/vendor/bin/phpunit -c  build/wp-content/plugins/swiftype-search/Tests/phpunit.xml
    - save_cache:
        paths:
        - ~/.composer/cache/
        key: v1-composer-dependencies

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
