version: 2

jobs:
  build:
    docker:
    - image: circleci/php:5.6-browsers
    - image: mysql:5.7
      environment:
        MYSQL_DATABASE: wptest
        MYSQL_USER: wptest
        MYSQL_PASSWORD: wptest
        MYSQL_RANDOM_ROOT_PASSWORD: "true"
    environment:
      WP_VERSION: "5.0"
      MYSQL_DATABASE: wptest
      MYSQL_USER: wptest
      MYSQL_PASSWORD: wptest
    working_directory: ~/repo
    steps:
    - run:
        name: Downloading WP
        command: wget -nv -O /tmp/wordpress.tar.gz https://github.com/WordPress/wordpress-develop/tarball/$WP_VERSION
    - run:
        name: Creating WP directory
        command: mkdir wordpress
    - run:
        name: Extracting WP from tarball
        command: tar --strip-components=1 -zxmf /tmp/wordpress.tar.gz -C wordpress
    - checkout:
        path: wordpress/src/wp-content/plugins/swiftype-search
    - run:
        name: Updating wp-test-config.php
        command: |
          cat wordpress/wp-tests-config-sample.php |
          sed "s/youremptytestdbnamehere/$MYSQL_DATABASE/" |
          sed "s/yourusernamehere/$MYSQL_USER/" |
          sed "s/yourpasswordhere/$MYSQL_PASSWORD/" |
          sed "s/localhost/127.0.0.1/" > wordpress/wp-tests-config.php
    - run: cat wordpress/wp-tests-config.php
